version: "3.9"

services:
  mysql:
    image: mysql:8.1
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Tedy@120917
      MYSQL_DATABASE: bookstore_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    image: akshayana/bookstore-backend:latest
    container_name: spring_backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookstore_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Tedy@120917
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    command: ["mvn", "spring-boot:run"] 
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    image: akshayana/bookstore-frontend:latest
    container_name: angular_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mysql_data:
