name: CI/CD - Build, Push, and Deploy to EC2 AWS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Images
      - name: Build and Push Docker Images
        run: |
          docker compose build --no-cache
          docker compose push

      # Step 4: Copy docker-compose.yml and db_init/ to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            docker-compose.yml
            db_init/
          target: ~/app

      # Step 5: Deploy on EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            echo "Stopping old containers..."
            docker compose down -v || true

            echo "Pulling new images..."
            docker compose pull

            echo "Starting containers..."
            docker compose up -d

            echo "Cleaning unused resources..."
            docker system prune -f
