name: CI/CD - Build, Push, and Deploy to EC2 AWS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 2: Build and Push Docker Images
      - name: Build and Push Docker Images
        run: |
          echo "🔨 Building and pushing Docker images..."
          docker compose build --no-cache
          docker compose push

      # Step 3: Copy docker-compose.yml and db_init folder to EC2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            docker-compose.yml
            db_init/
          target: "~/app"

      # Step 4: Deploy to EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🚀 Starting deployment..."
            cd ~/app

            echo "🧹 Cleaning old containers..."
            docker compose down -v || true

            echo "📦 Pulling latest images..."
            docker compose pull

            echo "🆙 Starting containers..."
            docker compose up -d

            echo "🧽 Pruning unused Docker data..."
            docker system prune -f

            echo "✅ Deployment complete!"
